# -*- coding: utf-8 -*-
"""Task1.population_distribution.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pw20KzkruobOBuSIwrgDvt1kKdegZ5Fv
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('API_SP.POP.TOTL_DS2_en_csv_v2_69.csv',skiprows=4)
print(df.head())

df.columns

poupulation_2020=df['2020'].dropna()
plt.hist(poupulation_2020,bins=20)
plt.title('Population Distribution across Countries (2020)')
plt.xlabel("Population")
plt.ylabel("Number of Countries")
plt.show()